export const paths = {
  home: '/',
  about: '/about',
  services: '/services',
  serviceDetail: (slug: string) => `/services/${slug}`,
  blog: '/blog',
  blogPost: (slug: string) => `/blog/${slug}`,
  support: '/support',
  privacyPolicy: '/privacy-policy',
  termsOfService: '/terms-of-service',
  trackLookup: '/track',
  track: (orderId: string) => `/track/${orderId}`,
  login: '/login',
  signup: '/signup',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',

  order: '/order',
  checkout: (step: string) => `/order/checkout/${step}`,
  confirmation: (orderId: string) => `/order/confirmation/${orderId}`,

  account: '/account',
  accountOrders: '/account/orders',
  accountOrder: (id: string) => `/account/orders/${id}`,
  accountTickets: '/account/tickets',
  accountTicket: (id: string) => `/account/tickets/${id}`,
  accountProfile: '/account/profile',
  verifyEmail: '/account/verify-email',

  admin: '/admin',
  adminOrders: '/admin/orders',
  adminOrder: (id: string) => `/admin/orders/${id}`,
  adminCustomers: '/admin/customers',
  adminCustomer: (id: string) => `/admin/customers/${id}`,
  adminCatalog: '/admin/catalog',
  adminZones: '/admin/zones',
  adminBanner: '/admin/banner',
  adminTickets: '/admin/tickets',
  adminTicket: (id: string) => `/admin/tickets/${id}`,
  adminBlog: '/admin/blog',
  adminBlogPost: (id: string) => `/admin/blog/${id}`,
  adminSettings: '/admin/settings',
  adminAdmins: '/admin/admins',
  adminWalkIn: '/admin/walk-in',
} as const
